### PR TITLE
Add .NET Standard csproj, introduce flags for NETSTANDARD2_0

### PR DESCRIPTION
**Pull request by claytondus**
A quick attempt to get the SDK building under .NET Standard 2.0.  Several features that use full framework APIs have been flagged out:
-AppSettings configuration. Use environment vars. 
-AddFraudCheck (does not detect IP from HttpContext) 
-SIMResponse does not populate from form 
-createFingerPrintController 
-getAUJobDetailsController 
-getAUJobSummaryController

### CODE REVIEW

**Comment by dansiegel** [comment]
This seems to me to be the complete wrong approach. One of the benefits of the SDK Style project is the ability to easily multi-target. A far better approach would be to update the existing project to a SDK Style project which could then target net35 like the existing sdk in addition to .NET Standard. I would also suggest targeting a lower version like 1.4 for better cross platform compatibility. Only targeting netstandard2.0 would force UWP developers to target the Fall Creators Update which many people aren't ready to do.

**Comment by mmikirtumov** [comment]
May be it will be better to commit these changes in core branch. Or maybe @dansiegel  you can create new branch and allow @claytondus to commit to that branch. And after add some note in Readme and other developers can find .Net Core version easy and do not block them.

Thanks

**Comment by Purushottamlpa** [comment]
Thanks for the request. We are working on this and will provide .NET standard support in next major release.

**Comment by mpetito** [comment]
Any update on timeline for .NET Standard support?

**Comment by chsriniv9** [comment]
We are working on releasing .Net Core sdk and should be available in July.

**Comment by nothingalike** [comment]
It is now October. Any update?

**Comment by chsriniv9** [comment]
Team,

ANET .Net Core SDK Beta Release is available in the [repo](https://github.com/AuthorizeNet/dotnet-core-sdk-beta). The beta release took longer than anticipated, apologies for the delay. Please use this release and provide if there are any feedback.

Thanks again for your patience and support !!

**Comment by gnongsie** [comment]
Due to the presence of the ANET .Net Core Beta SDK in the [repo](https://github.com/AuthorizeNet/dotnet-core-sdk-beta), I will be closing this PR.

Kindly reopen if any issues need further discussion.

**Pull request closed without merging**
